name: "Tag PRs with merge conflicts"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolved
  # We recommend `pull_request_target` so that GitHub secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "conflict"
          removeOnDirtyLabel: "conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "⚠️ This Pull Request has conflicts. Please resolve them before we can review the changes."
          commentOnClean: "✅ The conflicts have been resolved! A collaborator will review the Pull Request soon."
